# Generated by Django 5.0 on 2024-02-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_cart_is_ordered'),
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Payment Pending', 'Payment Pending'), ('Unordered', 'Unordered')], default='Unordered', max_length=15),
        ),
    ]
