# Generated by Django 5.0 on 2024-02-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_cart_is_ordered_cart_order_cart_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_status',
            field=models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Preparing', 'Preparing'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Unconfirmed', max_length=15),
        ),
    ]
