# Generated by Django 5.0 on 2024-02-13 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_cart_delivery_status'),
        ('orders', '0016_remove_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='orders.order'),
        ),
    ]
