# Generated by Django 5.0 on 2024-01-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='unknown.jpg', null=True, upload_to='users/cover_pictures'),
        ),
    ]
