# Generated by Django 5.0 on 2024-02-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
